version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "20:26"
    open-pull-requests-limit: 0
    groups:
      dev-prod-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
    reviewers:
      - "Hemal-Botadra"