version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "15:18"
    groups:
      dev-dependencies:
        patterns:
          - "*"
    reviewers:
      - "Hemal-Botadra"